### ISSUE TITLE
Web page not available 

### ISSUE THREAD

**Issue by MeeWantCookiee** [probonopd/irdb#105]
Hello, 

I was trying to use DIYRemote on my S6 (it's running Lineage OS), but when I try to find codes it says "the website could not be loaded because:  net::ERR_NAME_NOT_RESOLVED".

I am also having difficulties trying to access the database via other devices (S10 and PC), without any success.

Is that a fault from my side or are there Issues?

**Comment by Slion** [comment]
Same here, looks like http://irdb.tk/ is down.

**Comment by Slion** [comment]
Looks like a duplicate of #28 and should be closed. The doc ought to be updated though to remove reference to that website.

**Comment by Slion** [comment]
There is still a reference to it a few lines below. BTW does that mean that DIYRemote is not usable?

**Comment by probonopd** [comment]
Right. Fixed. Not sure about DIYRemote, if it still relies on the old website then it is not usable anymore.
