### ISSUE TITLE
New files breaking conventions

### ISSUE THREAD

**Issue by bengtmartensson** [probonopd/irdb#150]
Unfortunately, I discovered yesterday that there has been a number of commits recently, that breaks the established conventions for this project.

1. There has been a number of files that uses tab separated fields, instead the previously used comma separad fields ("csv"). For example: `codes/Aiwa/Tapedeck/AD-WX929`
2. Some new remotes do not adhere to the `<manufacturer>/<devicetype>/<device>,<subdevice>.csv` file name scheme, mandated in the README file. Particularly bad it is when the directory depth is changed, i.e. when `codes/*/*/*` does not consist of readable files (but possibly directories). For Example: `codes/Aiwa/Tapedeck/AD-WX929` (filename do not adhere), `codes/Wowee/ Robot Dog/Chippies/Chippies` (directory path does not adhere, and ... _a leading space_ in Robot Dog!!)
3. At least on file contains at least one empty line. `codes/RME/ADI DAC2/ADI DAC2`

Also for compatibility with many programs, I ask that `NEC` is not used as protocol name, since it does not contain any repeat informatsion. Instead e.g. `NEC1` (or NEC2) should be used, since it repeats.

If this project is to be considered as a data base to be readable from programs, not only humans, these convention violations are really a problem. 

Is there a need for discussion (I am more than open for this), or can I just ask for these "hickups" to be fixed?

Some of the new files say "Captured with IrScrutinizer...". Note that said program contains an export format "IRDB CSV" which generates files (but not file names!) in the right format.

@SS72post: Thank you very mucn for your contributions, but they are unfortunately not useful in the present form.

**Comment by probonopd** [comment]
Ouch. Sorry I didn't catch these.

For the future, maybe we should have some sort of automated test that runs on each pull request and checks the submissions.
In the meantime, we should probably roll back the repository to 44744ca?

**Comment by probonopd** [comment]
Moved what we had so far to jan2024 branch and reset the master branch to before the commits in question.

**Comment by bengtmartensson** [comment]
Actually, the files, which all appear to be from user @SS72post, appears to be, at least a subset, interesting. The non-conforming files are all available in the branch jan2024, so "you" just need to check out that branch and fix it, and make a PR. @SS72post, are you in?

**Comment by bengtmartensson** [comment]
fixed in 0fc69be03e6b243c6df22bb53be2d70b8baaa71b

**Comment by probonopd** [comment]
Thank you very much for cleaning up @bengtmartensson 👍
