### ISSUE TITLE
Looking to use and expand the database

### ISSUE THREAD

**Issue by luispl77** [probonopd/irdb#152]
Hello,
I am developing a device which is very cheap and let's users analyze any infrared signal, and reconstruct it.
I really like the simplicity and efficiency of defining codes with just protocol, device, subdevice, function. 

I would like to integrate this database in my software, and further expand it with every user of my device. If that seems alright, could I get a contact from the owner,  @probonopd , to discuss the implementation? 

Thank you, 
Luís

My discord username: luispl77

**Comment by probonopd** [comment]
Hello @luispl77, thanks for contacting me. Basically I'm interested in how you or your users could contribute back to this project (e.g., possibly your software could collect codes from your users and submit them as pull requests here, or something like that). You can reach me at probono at puredarwin dot org.

**Comment by luispl77** [comment]
Hello again @probonopd

I have sent you an email to discuss implementation of the database in my product. 
I will patiently wait for your reply, thank you!
