### ISSUE TITLE
Strex projector

### ISSUE THREAD

**Issue by Tsjippy** [probonopd/irdb#164]
Thank you for this! Very usefull.

I have a  [Strex projector](https://www.amazon.nl/-/en/Strex-Beamer-Lumens-Stream-Projector/dp/B0BM4HFV95). I am trying to figure out if the ir codes they use are similiar of something else that is out there.

How do I find the codes for it?

Or how do I figure out if there is another suplier that is using it?
Raw code for the power button:
```
8998     4530      530      566      554      588
      531      588      530     1688      554     1688
      554     1688      553      564      554     1706
      543     1691      546     1710      530     1688
      552      588      530     1703      539      588
      531     1692      553      566      556      563
      555      564      555     1686      563     1704
      530      588      531      589      531      589
      530      569      553     1688      554     1701
      546      608      507      586      530     1687
      555     1711      531     1700      542     1689
      554    39309
```

Thank you

**Comment by bengtmartensson** [comment]
The given codes decodes fine in IrScutinizer: NEC: {D=184,S=87,F=12}. (Copy to clipboard, paste into IrScrutinizer's Scrutinize signal window, press Scrutinize.) So if you capture the rest that will do it.

**Comment by Tsjippy** [comment]
Thanks that’s awesome

I was hoping to see if it was the same as another brand because I want to use my google chromecast remote as a remote for the projector. So knowing the signal is like the one of Nec I selected the NEC brand on the list of tv’s to choose from on the chromecast, but it didn’t work. Too bad
