### ISSUE TITLE
Find an alternative solution for rawgit

### ISSUE THREAD

**Issue by arthurlutz** [probonopd/irdb#17]
By reading the README I discover rawgit which seems like a nice idea/CDN. Unfortunately rawgit is shutting down, see the announcement on  https://rawgit.com/

**Comment by probonopd** [comment]
https://gitcdn.xyz/?

**Comment by probonopd** [comment]
https://github.com/probonopd/irdb/commit/ab5ee23a629d5836caebf91ba85d8ec92e50be14

Thanks for having brought this up @arthurlutz
