### ISSUE TITLE
Lamptan  Led Mult-Smart Ceiling  Lamp   ir codes

### ISSUE THREAD

**Issue by johng2001** [probonopd/irdb#20]
READY
1  power
Hash:
5A691DC4
For IR Scope/IrScrutinizer:
+9000 -4350 +650 -500 +600 -500 +650 -500 +600 -500 +650 -450 +650 -1600 +600 -550 +600 -1600 +600 -1650 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -1600 +650 -500 +600 -1650 +600 -1600 +650 -500 +600 -500 +650 -1600 +600 -500 +600 -1650 +600 -1650 +600 -1600 +600 -550 +600 -1650 +600 -1600 +650 -500 +600 -1600 +650 -500 +600 -500 +600 -550 +600 -127976
For Arduino sketch:
unsigned int raw[68] = {9000,4350,650,500,600,500,650,500,600,500,650,450,650,1600,600,550,600,1600,600,1650,600,1650,600,1650,600,500,600,1650,600,1600,650,500,600,1650,600,1600,650,500,600,500,650,1600,600,500,600,1650,600,1650,600,1600,600,550,600,1650,600,1600,650,500,600,1600,650,500,600,500,600,550,600,};
irsend.sendRaw(raw,68,38);

Protocol NEC1, device 160, subdevice 183, OBC 233

pronto hex
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 05F7 015B 0057 0016 0E6C

UIE HEX
00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 21 22 22 12 21 22 11 21 22 21 22 12 11 13 82 45
======================================================================================
2  night
Hash:
260BE260
For IR Scope/IrScrutinizer:
+9000 -4400 +550 -550 +600 -500 +600 -550 +600 -500 +600 -500 +600 -1650 +600 -550 +550 -1650 +600 -1650 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -1650 +550 -550 +600 -1650 +600 -1650 +550 -550 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -1600 +600 -1650 +600 -550 +550 -1650 +600 -550 +600 -1600 +600 -550 +600 -500 +600 -550 +550 -550 +600 -127976
For Arduino sketch:
unsigned int raw[68] = {9000,4400,550,550,600,500,600,550,600,500,600,500,600,1650,600,550,550,1650,600,1650,600,1650,600,1650,600,500,600,1650,600,1650,550,550,600,1650,600,1650,550,550,600,1650,600,500,600,1650,600,1650,600,1600,600,1650,600,550,550,1650,600,550,600,1600,600,550,600,500,600,550,550,550,600,};
irsend.sendRaw(raw,68,38);

Protocol NEC1, device 160, subdevice 183, OBC 245

Pronto Hex
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 05F7 015B 0057 0016 0E6C

UEI HEX
00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 21 22 22 12 21 22 12 12 22 21 21 21 11 13 82 45

======================================================================
3 bright +
Hash:
F8B41164
For IR Scope/IrScrutinizer:
+9000 -4400 +600 -500 +600 -550 +550 -550 +600 -500 +600 -550 +600 -1600 +600 -550 +600 -1650 +600 -1600 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -1600 +600 -550 +600 -1650 +550 -550 +600 -1650 +600 -500 +600 -1650 +600 -500 +600 -550 +550 -1650 +600 -550 +600 -1600 +600 -550 +600 -1650 +550 -550 +600 -127976
For Arduino sketch:
unsigned int raw[68] = {9000,4400,600,500,600,550,550,550,600,500,600,550,600,1600,600,550,600,1650,600,1600,600,1650,600,1650,600,500,600,1650,600,1650,600,500,600,1650,600,1650,600,1600,600,550,600,1650,550,550,600,1650,600,500,600,1650,600,500,600,550,550,1650,600,550,600,1600,600,550,600,1650,550,550,600,};
irsend.sendRaw(raw,68,38);

Protocol NEC1, device 160, subdevice 183, OBC 171

Pronto HEX
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 05F7 015B 0057 0016 0E6C

UEI HEX
00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 21 22 22 12 21 22 21 21 21 21 12 12 12 13 82 45

=========================================================================================

4  bright -
Hash:
4D5F4072
For IR Scope/IrScrutinizer:
+9000 -4400 +600 -500 +600 -550 +600 -500 +600 -500 +600 -550 +600 -1600 +600 -550 +600 -1650 +600 -1600 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -500 +600 -500 +600 -1650 +600 -1650 +600 -1650 +600 -1600 +600 -550 +600 -1650 +600 -1600 +600 -1650 +600 -500 +600 -550 +600 -500 +600 -550 +550 -1650 +600 -550 +600 -127976
For Arduino sketch:
unsigned int raw[68] = {9000,4400,600,500,600,550,600,500,600,500,600,550,600,1600,600,550,600,1650,600,1600,600,1650,600,1650,600,500,600,1650,600,1650,600,500,600,1650,600,500,600,500,600,1650,600,1650,600,1650,600,1600,600,550,600,1650,600,1600,600,1650,600,500,600,550,600,500,600,550,550,1650,600,550,600,};
irsend.sendRaw(raw,68,38);

Protocol NEC1, device 160, subdevice 183, OBC 188

Pronto HEX
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 05F7 015B 0057 0016 0E6C

UEI HEX
00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 21 22 22 12 21 21 12 22 21 22 21 11 12 13 82 45
======================================================================

5 K+
Hash:
4AB3764
For IR Scope/IrScrutinizer:
+9000 -4400 +600 -500 +600 -550 +600 -500 +600 -500 +600 -550 +600 -1600 +600 -550 +600 -1650 +550 -1650 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -1650 +550 -1650 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -1600 +600 -550 +600 -500 +600 -550 +550 -550 +600 -1650 +550 -550 +600 -500 +600 -550 +600 -127976
For Arduino sketch:
unsigned int raw[68] = {9000,4400,600,500,600,550,600,500,600,500,600,550,600,1600,600,550,600,1650,550,1650,600,1650,600,1650,600,500,600,1650,600,1650,600,500,600,1650,600,1650,550,1650,600,1650,600,1650,600,500,600,1650,600,1650,600,1600,600,550,600,500,600,550,550,550,600,1650,550,550,600,500,600,550,600,};
irsend.sendRaw(raw,68,38);

Protocol NEC1, device 160, subdevice 183, OBC 239

Pronto HEX
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 05F7 015B 0057 0016 0E6C

UEI HEX
00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 21 22 22 12 21 22 22 21 22 21 11 12 11 13 82 45

===========================================================================
6 K-
Hash:
49D1C860
For IR Scope/IrScrutinizer:
+8950 -4400 +600 -550 +600 -500 +600 -500 +600 -550 +600 -500 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -1650 +550 -1650 +600 -550 +600 -1600 +600 -1650 +600 -550 +550 -1650 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -1650 +550 -550 +600 -500 +600 -1650 +600 -500 +600 -1650 +600 -550 +550 -550 +600 -500 +600 -127976
For Arduino sketch:
unsigned int raw[68] = {8950,4400,600,550,600,500,600,500,600,550,600,500,600,1650,600,500,600,1650,600,1650,600,1650,550,1650,600,550,600,1600,600,1650,600,550,550,1650,600,1650,600,1650,600,500,600,1650,600,500,600,1650,600,1650,600,1650,550,550,600,500,600,1650,600,500,600,1650,600,550,550,550,600,500,600,};
irsend.sendRaw(raw,68,38);

Protocol NEC1, device 160, subdevice 183, OBC 235

Pronto HEX
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 05F7 015B 0057 0016 0E6C

UEI HEX
00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 21 22 22 12 21 22 21 21 22 21 12 12 11 13 82 45
=================================================================================

7 color
Hash:
77739D36
For IR Scope/IrScrutinizer:
+9000 -4400 +600 -500 +600 -550 +600 -500 +600 -550 +550 -550 +600 -1650 +600 -500 +600 -1650 +600 -1600 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -500 +600 -550 +600 -1600 +600 -1650 +600 -550 +550 -1650 +600 -550 +600 -1600 +600 -1650 +600 -1650 +600 -500 +600 -550 +600 -1600 +600 -550 +600 -1600 +600 -550 +600 -127976
For Arduino sketch:
unsigned int raw[68] = {9000,4400,600,500,600,550,600,500,600,550,550,550,600,1650,600,500,600,1650,600,1600,600,1650,600,1650,600,500,600,1650,600,1650,600,500,600,1650,600,500,600,550,600,1600,600,1650,600,550,550,1650,600,550,600,1600,600,1650,600,1650,600,500,600,550,600,1600,600,550,600,1600,600,550,600,};
irsend.sendRaw(raw,68,38);

NEC1, device 160, subdevice 183, OBC 172

Pronto HEX
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 05F7 015B 0057 0016 0E6C

UEI HEX
00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 21 22 22 12 21 21 12 21 21 22 21 12 12 13 82 45

===================================================================================

8 0.5h
Hash:
7ED89C56
For IR Scope/IrScrutinizer:
+8950 -4400 +600 -550 +600 -500 +600 -550 +600 -500 +600 -500 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -1650 +600 -1600 +600 -550 +600 -1600 +600 -1650 +600 -550 +550 -1650 +600 -550 +600 -1600 +600 -550 +600 -1650 +550 -1650 +600 -1650 +600 -1650 +600 -1600 +600 -1650 +600 -550 +600 -1600 +600 -550 +600 -500 +600 -500 +600 -550 +600 -500 +600 -127976
For Arduino sketch:
unsigned int raw[68] = {8950,4400,600,550,600,500,600,550,600,500,600,500,600,1650,600,500,600,1650,600,1650,600,1650,600,1600,600,550,600,1600,600,1650,600,550,550,1650,600,550,600,1600,600,550,600,1650,550,1650,600,1650,600,1650,600,1600,600,1650,600,550,600,1600,600,550,600,500,600,500,600,550,600,500,600,};
irsend.sendRaw(raw,68,38);

Protocol NEC1, device 160, subdevice 183, OBC 250

Pronto HEX
0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 05F7 015B 0057 0016 0E6C

UEI HEX
00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 21 22 22 12 21 21 21 22 22 22 12 11 11 13 82 45

============================================================================

9 1 h
Hash:
C76CEBFA
For IR Scope/IrScrutinizer:
+9000 -4350 +600 -550 +600 -500 +600 -550 +550 -550 +600 -500 +600 -1650 +600 -500 +600 -1650 +600 -1650 +600 -1650 +550 -1650 +600 -550 +600 -1600 +600 -1650 +600 -550 +550 -1650 +600 -550 +600 -500 +600 -500 +600 -1650 +600 -550 +550 -1650 +600 -550 +600 -1600 +600 -1650 +600 -1650 +600 -1650 +600 -500 +600 -1650 +600 -500 +600 -1650 +600 -500 +600 -127976
For Arduino sketch:
unsigned int raw[68] = {9000,4350,600,550,600,500,600,550,550,550,600,500,600,1650,600,500,600,1650,600,1650,600,1650,550,1650,600,550,600,1600,600,1650,600,550,550,1650,600,550,600,500,600,500,600,1650,600,550,550,1650,600,550,600,1600,600,1650,600,1650,600,1650,600,500,600,1650,600,500,600,1650,600,500,600,};
irsend.sendRaw(raw,68,38);

Protocol NEC1, device 160, subdevice 183, OBC 168

Pronto HEX

0000 006C 0022 0002 015B 00AD 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0016 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0041 0016 0041 0016 0041 0016 0016 0016 0041 0016 0016 0016 0041 0016 0016 0016 05F7 015B 0057 0016 0E6C

UEI HEX
00 00 2F 00 D0 06 11 A0 08 D0 01 1A 01 1A 01 1A 03 4E 01 1A 4D A6 11 A0 04 68 01 1A BB CE 22 01 11 11 21 22 22 12 21 21 11 21 21 22 22 12 12 13 82 45

**Comment by probonopd** [comment]
Please send a [pull request](https://help.github.com/articles/creating-a-pull-request/), thanks.
