### ISSUE TITLE
irdb.tk is down

### ISSUE THREAD

**Issue by bengtmartensson** [probonopd/irdb#28]
... since a few days.

**Comment by probonopd** [comment]
Should be back again for now but I am looking for someone to take over maintenance and operations eventually.

**Comment by bengtmartensson** [comment]
Time again...

**Comment by probonopd** [comment]
The hosting company upgraded the operating system and as a result broke the service.
I have contacted them.

**Comment by benfoxall** [comment]
Would it be possible to port irdb.tk to a static site and serve through github pages?

If the site source is available somewhere I could try and have a dig if you'd like.

**Comment by probonopd** [comment]
Well, the conversions the site offered will be hard to do using a static website. But @bengtmartensson's tools can do them.
And the codes on the website can be rendered to various formats using @bengtmartensson's tools, too.
Let me see how the hosting company responds.

**Comment by benfoxall** [comment]
Cool.  Hopefully the hosting company responds soon.

Might be relevant; a while ago I managed to compile [MakeHex](https://github.com/probonopd/MakeHex) to [WebAssembly](https://webassembly.org/) so it could be run within the browser.  Maybe the same approach may work for @bengtmartensson's tools too?

**Comment by bengtmartensson** [comment]
> a while ago I managed to compile MakeHex to WebAssembly so it could be run within the browser. Maybe the same approach may work for @bengtmartensson's tools too?

[IrpTransmogrifier](https://github.com/bengtmartensson/IrpTransmogrifier) is written in Java. Once upon a time, Java was "made for" running inside of browsers, now things are different ;-\ I guess there "must" be  some way to do it. 

@probonopd : can you open a "Discussions" area?

**Comment by probonopd** [comment]
Opened.

**Comment by bengtmartensson** [comment]
Any news?

**Comment by probonopd** [comment]
Unfortunately they answered that they had to upgrade the server, which now seemingly comes with different versions of the dependencies. Which means that the code would have to be re-worked, which I don't have the time to. I think we should do somehting "more modern" anyway.

**Comment by Nardol** [comment]
@probonopd could it be envisaged to release the irdb.tk source code?
Maybe some could help to modernize the code if it is the problem.

**Comment by probonopd** [comment]
Yes, it could be "envisaged". But I'd need to find the time to go through the source and clean it up. Volunteers?

**Comment by Nardol** [comment]
Why not... Which language and what about the database?

**Comment by probonopd** [comment]
Python, Java, and SQLite

**Comment by Nardol** [comment]
I do not wish to formulate any promise but sure I am interested in the project.

Which dependences are broken since the update?
And what would be the new requirements?

**Comment by probonopd** [comment]
Well. The old site was a dynamic one, while I'd like to move to a static one hosted entirely on GitHub.

**Comment by Nardol** [comment]
OK, I did not understand the idea to keep it as a dynamic website was definitely excluded :slightly_smiling_face:

**Comment by benfoxall** [comment]
I've been working [on a site that uses irdb](https://benjaminbenben.com/puckmote/) that might be useful if migrating to `irdb.tk` to GitHub pages.

![image](https://user-images.githubusercontent.com/51385/116985541-8a5f4900-acc4-11eb-999b-48aa635588e1.png)

It's completely static, and the content is loaded directly [from the jsdeliver](https://github.com/benfoxall/puckmote/blob/main/src/irdb.ts#L4) endpoint.  It has query-param based routing, so URLs work for linking.

To generate the timings, I'm using [WebAssembly](https://github.com/probonopd/irdb/issues/28#issuecomment-817321693), but if more complex responses are needed, maybe something like [AWS lambda](https://aws.amazon.com/lambda/) would be an option instead?  I'm not actually sure what content was served from irdb.tk!

I'd be happy to help out if this was the direction that you wanted to take with the site.

**Comment by probonopd** [comment]
Hello @benfoxall this sounds like a very interesting approach. Can you implement this using the codes from https://github.com/probonopd/irdb/ or would you need any changes in this repository?

**Comment by benfoxall** [comment]
Yep, it requests the codes directly from the repo via:

`https://cdn.jsdelivr.net/gh/probonopd/irdb@master/codes/index`

No changes would be needed.

**Comment by probonopd** [comment]
Closing because irdb.tk in its old form will not come back due to the maintenance overhead needed to keep a dynamic web service running with Python and Java. Let's open new tickets on how to e.g., render static pages for rendered codes if so desired.
