### ISSUE TITLE
Need Help: RAW IR Code Conversion Not working

### ISSUE THREAD

**Issue by cylon147** [probonopd/irdb#29]
Thanks for Creating irdb.

Somehow I can't figure our How to convert RAW ir code to Pronto hex. I have Used irdb API but its throwing an error.

Can you please help me out.

[http://irdb.tk/api/decode/3477,3477,885,2634,885,885,885,885,885,885,885,2634,885,2634,885,2634,885,2634,885,2634,885,885,885,885,885,885,885,2634,885,2634,885,2634,885,2634,885,885,885,2634,885,2634,885,885,885,885,885,885,885,885,885,885,885,885,885,2634,885,2634,885,885,885,885,885,885,885,885,885,885,3477,3477,885,2634,885,885,885,885,885,885,885,2634,885,2634,885,2634,885,2634,885,2634,885,885,885,885,885,885,885,2634,885,2634,885,2634,885,2634,885,885,885,2634,885,2634,885,885,885,885,885,885,885,885,885,885,885,885,885,2634,885,2634,885,885,885,885,885,885,885,885,885,885,3477,3477,885,13946,3477,3477,885,885,885,885,885,2634,885,885,885,885,885,885,885,885,885,885,885,885,885,885,885,2634,885,885,885,885,885,885,885,885,885,885,885,885,885,2634,885,2634,885,885,885,2634,885,2634,885,885,885,885,885,885,885,2634,885,2634,885,885,885,2634,885,2634,885,885,885,885,3477,3477,885,885,885,885,885,2634,885,885,885,885,885,885,885,885,885,885,885,885,885,885,885,2634,885,885,885,885,885,885,885,885,885,885,885,885,885,2634,885,2634,885,885,885,2634,885,2634,885,885,885,885,885,885,885,2634,885,2634,885,885,885,2634,885,2634,885,885,885,885,3477,3477,885](url)

**Comment by probonopd** [comment]
Hi @cylon147. Please try to decode your code using https://github.com/bengtmartensson/IrScrutinizer/releases/.

**Comment by cylon147** [comment]
I have Tried Decoding with IrScrutinizer and it works. As I am working with few 100+ codes I was looking a Cloud API solution like irdb API.

**Comment by cylon147** [comment]
@probonopd I really appreciate if you can Help me out on this. 

Please

Awaiting your erliest reply

**Comment by bengtmartensson** [comment]
What do you want to achieve? "CloudAPI" sounds more like an attempted "how" then "what".

If bulk decoding is what you want to do, then put all your signals into a text file and import it to IrScrutinizer -- it has very powerful importing capacities. If you really are after an API for decoding IR signals, [look at IrpTransmogrifier](https://bengtmartensson.github.io/IrpTransmogrifier/)

**Comment by cylon147** [comment]
Thanks for the Reply @bengtmartensson

IrScrutinizer - is a windows app. It works but its not the Solution I m looking for. The Device I am working on is an Embedded Thermostate witch supports loading LUA script with IR codes for Temperature. It supports Pronto Hex only as an IR code.

Now the Codes I have are all in Raw IR so a web API like [](http://irdb.tk/convert/) will work but somehow irdb.tk is also not working for Converting the Raw IR code to Pronto Hex.

Please let me know if you need MOre information.

**Comment by probonopd** [comment]
http://irdb.tk/api is retired, please use something like IrScrutinizer. It should be able to convert your codes from Raw to Pronto Hex.
