### ISSUE TITLE
More metadata?

### ISSUE THREAD

**Issue by JohnVeness** [probonopd/irdb#36]
Many thanks for this project, which is very useful.

Have you considered adding extra metadata, such as which particular model TV (or whatever) a codeset, or even individual codes, work on? With consumer user-experiences like Harmony, the user can search by make and model number which would be useful for irdb too, rather than just presenting the user with a list of generic codesets to try.

It would also be useful to have some kind of indication as to whether anyone has done a bulk test of all 256 codes in a particular set, to check for hidden discretes and other functions. In other words, if a user finds a codeset from irdb with just a toggle power command, it would be nice to know whether it has been "proven" that the device only has toggle power, or whether it is just that someone learnt the original remote buttons and didn't systematically try any other codes.

**Comment by probonopd** [comment]
Thanks @JohnVeness.

Actually I intentionally removed the individual models because I feel we cannot keep up with hundreds of Samsung TV models that come out every year... (just as an example).

And no, I don't think anyone has systematically tested the "bulk" yet. But you are free to! :+1:

**Comment by probonopd** [comment]
It's worth noting that we compiled this database from all sorts of sources and contributions, no one in this project actually owns all of those devices!
