### ISSUE TITLE
Invalid TLS certificate for irdb.tk

### ISSUE THREAD

**Issue by shannah** [probonopd/irdb#38]
The TLS certificate for irdb.tk doesn't seem to be valid

![image](https://user-images.githubusercontent.com/2677562/92326891-5f740680-f00a-11ea-83c0-f88687f19958.png)

Looks like perhaps it is for the wrong domain name.

**Comment by bengtmartensson** [comment]
irdb.tk does not exist any more, and no reincarnation presently planned (#28). So this issue is not relevant any more.
