### ISSUE TITLE
Is there encode api call ? - e.g http://irdb.tk/api/encode/ option ?

### ISSUE THREAD

**Issue by nodecentral** [probonopd/irdb#42]
Hi,

I’ve been having a go at the api and I was wondering is there a ‘encode’ option ? 

Something that would allow me to send the ‘POWER’ function, along with the protocol, devicetype etc. and get back something I could then send out/use,  e.g in its pronto format ?

`    {
      "function": "2", 
      "protocol": "NECx2", 
      "subdevice": "7", 
      "devicetype": "TV", 
      "device": "7", 
      "functionname": "POWER"
    },  `

**Comment by probonopd** [comment]
Hello @nodecentral. There is no such API call, clients need to render the codes on the client side. Check out the excellent http://www.harctoolbox.org/ in particular.
