### ISSUE TITLE
irdb.tk don't update codes after merge

### ISSUE THREAD

**Issue by dobbelina** [probonopd/irdb#46]
Hi!

I updated the Sony codes below a few days ago but i don't see them
at irdb.tk ?
https://github.com/probonopd/irdb/blob/master/codes/Microsoft/Windows%20Media%20Center/4%2C15.csv

**Comment by probonopd** [comment]
Yes, irdb.tk and this repository are not really synced with each other. I am thinking of retiring irdb.tk in favor of this repository.

**Comment by dobbelina** [comment]
That would be a shame.
irdb.tk was the reason i found this repo.
Please don't retire the converter though, that one is neccesary
to add codes to the database.

**Comment by probonopd** [comment]
[IrScrutinizer](http://www.harctoolbox.org/IrScrutinizer.html) should be able to do the same.

**Comment by probonopd** [comment]
I have retired irdb.tk in favor of this repository.
