### ISSUE TITLE
convert codes to other formats

### ISSUE THREAD

**Issue by pumper** [probonopd/irdb#48]
Hi I have a question and found my answer no where else so ask it here.
How can I convert the IR signal information that are in this repository to Pronto Hex or RAW codes that actually I can use them.
I know that I can use http://irdb.tk/convert/ for one device but I want to do it my self for my app.
thank .

**Comment by bengtmartensson** [comment]
You can use IrScrutinizer. Just import the signal(s) and then export them in desired format. If you need exact instructions, tell us exactly what you want to do.
