### ISSUE TITLE
Potential Project

### ISSUE THREAD

**Issue by ApplebaumIan** [probonopd/irdb#51]
As per the IRDB license I'm writing to inform you that I would like to use your database for a future project. The App would allow users to add their IR capable devices to their homeIOT systems. I would also like to allow users to contribute to the database with new devices. Should we create some sort of bot that creates Pull requests for the newly captured device or fork the repository and add the new devices there? It's a bit of a conundrum because users could potentially mistakenly add the same device that is already present in the DB. 

Best Regards,
~ Ian Applebaum

**Comment by probonopd** [comment]
Hello @ApplebaumIan, thanks for reaching out.

Ideally your app would send codes to your backend, and then a skilled person from your project/company would manually review them, and create pull requests here.

Would this work for you?
