### ISSUE TITLE
 500 Internal Server Error

### ISSUE THREAD

**Issue by gadashehada** [probonopd/irdb#59]
This error comes when I try to access the website '**https://irdb.tk/codes/**'. 
I want to get an Epson projector IR command.

![Screenshot (2)](https://user-images.githubusercontent.com/43495144/116600769-584f8f00-a932-11eb-99df-f7d1bc011397.png)

**Comment by probonopd** [comment]
Hello, the irdb.tk website is [down](https://github.com/probonopd/irdb/issues/28), please look for the codes in this repsitory, specifically in
https://github.com/probonopd/irdb/tree/master/codes/Epson.

**Comment by gadashehada** [comment]
Can't you just give me the pronto?
Because I didn't understand the table in the repository.
