### ISSUE TITLE
Using database in OTRTA

### ISSUE THREAD

**Issue by nibdev** [probonopd/irdb#8]
Hi, 

i'd like to use your database in my app (OTRTA), in the next version.
You will find it here when its ready: 
http://github.com/nibdev/otrta

**Comment by probonopd** [comment]
Hi @nibdev sure, go ahead, since your project is MIT licensed you are free to use the database. Please ping me when it is ready for testing.

**Comment by nibdev** [comment]
Thanks, I'll leave a comment here as soon as its online
