### ISSUE TITLE
License of IRDB

### ISSUE THREAD

**Issue by mikebarnick** [probonopd/irdb#83]
We have a product that uses the IRDB data you provide.  We are adding the license statement now.  We can also send you a couple products as required.  I would like to ask that we send 2 instead of 3 as it is a hardware product and it costs us a fair amount of money.  
https://quantumintegrate.com/pages/starter-bundle
Just send us your address and we'll get the products to you.  I'll include the IR Remote kit also so you can play with it.
Sincerely, 
Mike Barnick
Please send all correspondence to mbarnick@quantumintegrate.com as I don't use GitHub often.

**Comment by probonopd** [comment]
Thanks for the notice, followed up by mail, hence closing here.
